<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-8UBV4BQ" failures="5" tests="5" name="Default test(failed)" time="0.49" errors="0" timestamp="2022-04-15T13:00:09 ICT">
  <testcase classname="com.source.dao.test.UsersDAOTest" name="selectByIdTest" time="0.34">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user &amp;apos;sa&amp;apos;. ClientConnectionId:5c84f66b-a83b-4571-99d2-3ff6d6c16550">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:5c84f66b-a83b-4571-99d2-3ff6d6c16550
at com.source.utils.XJDBC.query(XJDBC.java:74)
at com.source.dao.UsersDAO.selectBySql(UsersDAO.java:79)
at com.source.dao.UsersDAO.selectAll(UsersDAO.java:72)
at com.source.dao.test.UsersDAOTest.selectByIdTest(UsersDAOTest.java:129)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:5c84f66b-a83b-4571-99d2-3ff6d6c16550
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5560)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4289)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:88)
at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4227)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2978)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2628)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2471)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1470)
at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:915)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at com.source.utils.XJDBC.getStmt(XJDBC.java:38)
at com.source.utils.XJDBC.query(XJDBC.java:68)
... 31 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- selectByIdTest -->
  <testcase classname="com.source.dao.test.UsersDAOTest" name="testUpdate" time="0.002">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.source.model.Users.getHoTen()&amp;quot; because &amp;quot;entity&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.source.model.Users.getHoTen()" because "entity" is null
at com.source.dao.UsersDAO.update(UsersDAO.java:46)
at com.source.dao.test.UsersDAOTest.testUpdate(UsersDAOTest.java:100)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate -->
  <testcase classname="com.source.dao.test.UsersDAOTest" name="testDelete" time="0.045">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user &amp;apos;sa&amp;apos;. ClientConnectionId:221684c4-2641-4a21-b979-c542adb1c0f6">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:221684c4-2641-4a21-b979-c542adb1c0f6
at com.source.utils.XJDBC.update(XJDBC.java:63)
at com.source.dao.UsersDAO.delete(UsersDAO.java:58)
at com.source.dao.test.UsersDAOTest.testDelete(UsersDAOTest.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:221684c4-2641-4a21-b979-c542adb1c0f6
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5560)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4289)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:88)
at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4227)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2978)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2628)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2471)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1470)
at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:915)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at com.source.utils.XJDBC.getStmt(XJDBC.java:38)
at com.source.utils.XJDBC.update(XJDBC.java:53)
... 30 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testDelete -->
  <testcase classname="com.source.dao.test.UsersDAOTest" name="deleteTest" time="0.001">
    <failure type="java.lang.RuntimeException" message="Test not implemented">
      <![CDATA[java.lang.RuntimeException: Test not implemented
at com.source.dao.test.UsersDAOTest.deleteTest(UsersDAOTest.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- deleteTest -->
  <testcase classname="com.source.dao.test.UsersDAOTest" name="selectAllTest" time="0.042">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user &amp;apos;sa&amp;apos;. ClientConnectionId:24cc0f65-c67f-4be1-8a56-fa78d7ec93b3">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:24cc0f65-c67f-4be1-8a56-fa78d7ec93b3
at com.source.utils.XJDBC.query(XJDBC.java:74)
at com.source.dao.UsersDAO.selectBySql(UsersDAO.java:79)
at com.source.dao.UsersDAO.selectAll(UsersDAO.java:72)
at com.source.dao.test.UsersDAOTest.selectAllTest(UsersDAOTest.java:120)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'sa'. ClientConnectionId:24cc0f65-c67f-4be1-8a56-fa78d7ec93b3
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:5560)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4289)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$000(SQLServerConnection.java:88)
at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4227)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2978)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2628)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2471)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1470)
at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:915)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
at com.source.utils.XJDBC.getStmt(XJDBC.java:38)
at com.source.utils.XJDBC.query(XJDBC.java:68)
... 31 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- selectAllTest -->
  <testcase classname="com.source.dao.test.UsersDAOTest" name="f" time="0.0">
    <ignored/>
  </testcase> <!-- f -->
</testsuite> <!-- Default test(failed) -->
